# Generated by Django 4.0.6 on 2022-08-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('sponsor_type', models.CharField(choices=[('JISMONIY', 'Jismoniy shaxs'), ('YURIDIK', 'Yuridik shaxs')], max_length=15)),
                ('balance', models.PositiveIntegerField()),
                ('sponsored', models.PositiveIntegerField(default=0)),
                ('phone_number', models.IntegerField()),
                ('company', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(choices=[('MODERATION', 'Moderatsiya'), ('NEW', 'Yangi'), ('APPROVED', 'Tasdiqlangan'), ('CANCELED', 'Bekor qilingan')], default='MODERATION', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField()),
                ('degree', models.CharField(choices=[('BACHELOR', 'Bakalavr'), ('MAGISTER', 'Magister')], max_length=10)),
                ('contract', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
