# Generated by Django 4.0.6 on 2022-08-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
